### ISSUE TITLE
Feedback

### ISSUE THREAD

**Issue by suminohana** [hopto-dot/Gelbooru-Downloader#3]
1 - I've read in another issue that the program can't download an image if it has less than a certain amount of tags. Why is that?
2 - It's great that it automatically downloads the images on their original size, and doesn't do any transcoding.
3 - If it already writes the tags into the image files's names, why creating an extra .txt for that? I see no reason for it. The image files already contain all the tags on the filename.
4 - I got some System.Net.WebException errors.
5 - Why not enable direct dowloading via an image's URL? It might sound pointless at first, but it's actually faster to download with the program than manually, even more so if you already have the links ready.
6 - Very convenient that the .exe can be opened directly, without having to drag it to cmd or copying the path.

**Comment by hopto-dot** [comment]
Thank you for the feedback.

1. This is the default - if you want to change this behaviour I have provided the ability to change it if you clone the repo, change the `minimumTagTotal` variable in `TagGroup.cs`, then build the project. I may add functionality to do with without having to change the code in the future.

3. It doesn't write all the tags into the file name, the filename has a length limit and other restrictions so I write the full tags to a text file.
4. Without more context, I'm afraid I can't fix this issue.
5. I agree, I'll add this.

**Comment by hopto-dot** [comment]
I have released a new version to address a couple of the things you mentioned
